### ISSUE TITLE
Remove default custom hostnames when setting up 

### ISSUE THREAD

**Issue by sumitramanga** [magenizr/Magenizr_Raygun#4]
Again, it is safe to say that if the API Key is added, then they are intending to set up Raygun's features! Spotting errors locally I would say is essential to not deploying bad code into production. So users can capture their errors as earlier as possible. Also, discoverability wise, they won't encounter this until they turn it on. At least when it's turn on, they can see what the impact is :)

**Comment by magenizr** [comment]
Hi @sumitramanga 

We had cases in Laravel projects where local and staging environments ( particularly cron jobs ) have pushed a large amount of fatal errors to the live account of Raygun and triggered false alerts.

How about moving `Excluded Hostnames` to the developer section and leave it disabled by default?

**Comment by sumitramanga** [comment]
Hi @magenizr In that case, I think we leave it as is! Perhaps we need a feature to avoid cron job errors from coming through instead. that could be a possibility? Just trying to find a way of integrating Raygun in local development so that production errors by real users can be avoided

**Comment by magenizr** [comment]
Hi @sumitramanga 

This has been moved to the `Developer` section and will be available in the next release.

![20240704-raygun-backend-02 (1)](https://github.com/magenizr/Magenizr_Raygun/assets/36174840/5f0bf93f-0eff-4da1-9ba9-1ea9c69d083b)

As discussed earlier, we'll leave the feature available for now so that developers can turn off Raygun completely for certain environments. Errors triggered by cronjob are not easy to identify unfortunately.

Regards,
John

**Comment by magenizr** [comment]
Release 1.1.1 has been published, thank you for your contribution 👍
